services:
  - type: web
    name: currency-converter-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXCHANGE_API_KEY
        sync: false
      - key: PORT
        value: 3000
      - key: BASE_CURRENCY
        value: USD
      - key: CACHE_TTL
        value: 7200000
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
    autoDeploy: true 